package jeex.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-04-10T22:48:34.571+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "TopicManagerService",
                  targetNamespace = "http://beans.ejb.jeex/") 
public class TopicManagerService extends Service {
    private final static String WSDL_PATH = (System.getProperty("user.home") + "/git/jeex/ws/wsdl/topic.wsdl");
    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://beans.ejb.jeex/", "TopicManagerService");
    public final static QName TopicPort = new QName("http://beans.ejb.jeex/", "topicPort");
    static {
        URL url = null;
        try {
            url = new URL(WSDL_PATH);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TopicManagerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", WSDL_PATH);
        }
        WSDL_LOCATION = url;
    }

    public TopicManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TopicManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TopicManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TopicManagerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TopicManagerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TopicManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Topic
     */
    @WebEndpoint(name = "topicPort")
    public Topic getTopicPort() {
        return super.getPort(TopicPort, Topic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Topic
     */
    @WebEndpoint(name = "topicPort")
    public Topic getTopicPort(WebServiceFeature... features) {
        return super.getPort(TopicPort, Topic.class, features);
    }

}
