package jeex.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-04-10T22:48:34.541+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://beans.ejb.jeex/", name = "topic")
@XmlSeeAlso({ObjectFactory.class})
public interface Topic {

    @WebMethod
    @RequestWrapper(localName = "listTopics", targetNamespace = "http://beans.ejb.jeex/", className = "jeex.ws.ListTopics")
    @ResponseWrapper(localName = "listTopicsResponse", targetNamespace = "http://beans.ejb.jeex/", className = "jeex.ws.ListTopicsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<jeex.ws.Topic_Type> listTopics();
}
